### ISSUE TITLE
Solving Navier-Stokes Equation

### ISSUE THREAD

**Issue by cancam** [xiaulinhu/pinn-pytorch#1]
Hi,

Thank you for this repository. Are you planning to add Navier-Stokes solver to the repository?

Baris.

**Comment by EdgeLLM** [comment]
Hi Baris,

Thanks for your enquiry. Pinn-pytorch is designed as highly configurable package and I am working hard to release Navier-Stokes and other solvers, stay tuned.

Xiaolin.

**Comment by cancam** [comment]
Thank you for your reply, I'm closing the issue. Looking forward to hear about news about NS solver.

Baris.
